export default {
  variants: {
    mainTitle:{
      fontWeight:'900',
      fontSize:'90px',
      textTransform:'capitalize'
    },
    mainSubTitle:{
      fontWeight:'900',
      fontSize:'18px',
      textTransform:'uppercase'
    },
    normal:{
      fontWeight:'400',
      fontSize:'14px',
      lineHeight:'24px',
    },
    h1:{
      fontWeight:'700',
      fontSize:'44px',
      lineHeight:'60.72px'
    },
    sectionTitle:{
      fontSize:'36px',
      lineHeight:'49.68px',
      fontWeight:'700',
      marginTop:'31px'
    },
    sectionSubtitle:{
      fontSize:'20px',
      lineHeight:'22.8px',
      fontWeight:'700',
      textTransform: 'uppercase',
    },
    callsTitle:{
      fontSize:'44px',
      lineHeight:'50px',
      fontWeight:'900'
    },
    introSection:{
      fontSize:'18px',
      marginTop:'10px',
      marginBottom:'10px',
      fontWeight:'900'
    },
    submenuItem:{
      fontSize:'13px',
      textDecoration:'none',
      textTransform:'capitalize'
    },
    menuItem:{
      fontSize:'15px',
      textDecoration:'none',
      textTransform:'uppercase'
    }
  }
}