import type { Metadata } from 'next';

import { justAnotherHand, quicksand } from '@/core/fonts/fonts.script';

import { ThemeRegistry } from './common/components';
import './globals.css';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} ${justAnotherHand.variable}`}>
        <ThemeRegistry>
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
